export const idDict = {
    "./img/Adon Olam.jpg" : "Adon Olam",
    "./img/Ahavah Rabbah.jpg" : "Ahavah Rabbah",
    "./img/Aleinu.jpg" : "Aleinu",
    "./img/Amidah.jpg" : "Amidah",
    "./img/Ashrei.jpg" : "Ashrei",
    "./img/Baruch Sheamar.jpg" : "Baruch Sheamar",
    "./img/El Baruch.jpg" : "El Baruch",
    "./img/Hallel.jpg" : "Hallel",
    "./img/Hallelu.jpg" : "Hallelu",
    "./img/Kaddish.jpg" : "Kaddish",
    "./img/Lecha Dodi.jpg" : "Lecha Dodi",
    "./img/Mi Chamochah.jpg" : "Mi Chamochah",
    "./img/Oseh Shalom.jpg" : "Oseh Shalom",
    "./img/Shema.jpg" : "Shema",
    "./img/Tzur Yisrael.jpg" : "Tzur Yisrael",
}
